version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
    groups:
      python-dependencies:
        patterns:
          - "*"