[package]
name = "taunicorn-python"
version = "0.1.4"
edition = "2024"
publish = false

[lib]
name = "_taunicorn"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "=0.29", default-features = false, features = ["abi3-py310","anyhow","bytes","extension-module","generate-import-lib","macros"]}
pyo3-async-runtimes = {version = "0.29", default-features = false, features = ["tokio-runtime"]}
anyhow = "1.0.91"
taunicorn = { path = "../taunicorn" }
